#!/usr/bin/env python3

import os
import argparse
import anndata as ad
import scvi

def integrate_with_scvi(
    adata: ad.AnnData,
    batch_key: str,
) -> tuple[ad.AnnData, scvi.model.SCVI]:
    """
    Fit scVI model to AnnData object
    """

    # Fixed parameters
    n_latent = 30
    n_layers = 2
    train_size = 0.85
    scvi_epochs = 300
    batch_size = 1024
    accelerator = "gpu"
    dispersion = "gene-cell"  # "gene"
    gene_likelihood = "zinb"
    latent_distribution = "normal"
    early_stopping = True
    early_stopping_patience = 20

    # Set parameters based on numerical instabilities
    threshold_cells = 3.05e6 # No. of cells in current PMDBS sc cohort
    if adata.n_obs > threshold_cells:
        plan_kwargs = {"lr": 1e-4}
        gradient_clip_val = 5.0
    else:
        # Defaults
        plan_kwargs = {"lr": 1e-3} 
        gradient_clip_val = None

    # Integrate the data with scVI
    # noise = ["doublet_score", "pct_counts_mt", "pct_counts_rb"]
    categorical_covariate_keys = None
    scvi.model.SCVI.setup_anndata(
        adata,
        layer="counts",
        batch_key=batch_key,
        # continuous_covariate_keys=noise,
        # categorical_covariate_keys=categorical_covariate_keys,
    )

    model = scvi.model.SCVI(
        adata,
        n_layers=n_layers,
        n_latent=n_latent,
        dispersion=dispersion,
        gene_likelihood=gene_likelihood,
    )

    model.train(
        train_size=train_size,
        max_epochs=scvi_epochs,
        early_stopping=early_stopping,
        early_stopping_patience=early_stopping_patience,
        accelerator=accelerator,
        gradient_clip_val=gradient_clip_val,
        plan_kwargs=plan_kwargs,
    )

    adata.obsm[args.latent_key] = model.get_latent_representation()  # type: ignore

    return (adata, model)


def main(args: argparse.Namespace):
    # Set the number of data loader workers
    scvi.settings.dl_num_workers = max(1, os.cpu_count() - 1)
    print(f"Using {scvi.settings.dl_num_workers} workers")

    # 0. Load data
    adata = ad.read_h5ad(args.adata_input)  # type: ignore
    # 2. Process data
    adata, model = integrate_with_scvi(adata, args.batch_key)
    # 3. Save the integrated adata and scVI model
    model.save(args.output_scvi_dir, overwrite=True)
    adata.write_h5ad(filename=args.adata_output, compression="gzip")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run scVI integration")
    parser.add_argument(
        "--latent-key",
        type=str,
        required=True,
        help="Latent key to save the scVI latent to",
    )
    parser.add_argument(
        "--batch-key",
        type=str,
        required=True,
        help="Key in AnnData object for batch information",
    )
    parser.add_argument(
        "--adata-input",
        type=str,
        required=True,
        help="AnnData object for a dataset",
    )
    parser.add_argument(
        "--adata-output",
        type=str,
        required=True,
        help="Output file to save AnnData object to",
    )
    parser.add_argument(
        "--output-scvi-dir",
        type=str,
        required=True,
        help="Output folder to save scVI model",
    )

    args = parser.parse_args()
    main(args)
