#!/usr/bin/env python3

import os
import argparse
import anndata as ad
import scvi


def label_with_scanvi(
    adata: ad.AnnData, model: scvi.model.SCVI
) -> tuple[ad.AnnData, scvi.model.SCANVI]:
    """
    Fit scANVI model to AnnData object
    """
    scanvi_epochs = 300
    batch_size = 1024
    accelerator = "gpu"
    dispersion = "gene-cell"  # "gene"
    gene_likelihood = "zinb"
    latent_distribution = "normal"
    early_stopping = True
    early_stopping_patience = 20

    print("Generating scANVI model from scVI")
    scanvi_model = scvi.model.SCANVI.from_scvi_model(
        model,
        adata=adata,
        labels_key="cell_type",
        unlabeled_category="Unknown",
    )

    print("Training scANVI model")
    scanvi_model.train(
        accelerator=accelerator,
        max_epochs=scanvi_epochs,
        early_stopping=early_stopping,
        early_stopping_patience=early_stopping_patience,
    )

    print("Generating scANVI latents and predictions")
    adata.obsm[args.latent_key] = scanvi_model.get_latent_representation(adata)
    adata.obs[args.predictions_key] = scanvi_model.predict(adata)

    return (adata, scanvi_model)


def main(args: argparse.Namespace):
    # Set the number of data loader workers
    scvi.settings.dl_num_workers = max(1, os.cpu_count() - 1)
    print(f"Using {scvi.settings.dl_num_workers} workers")

    # 0. Load data
    adata = ad.read_h5ad(args.adata_input)  # type: ignore
    model_path = args.scvi_outputs_dir
    model = scvi.model.SCVI.load(
        dir_path=model_path,
        adata=adata,
    )
    # 4. Get scANVI model
    adata, scanvi_model = label_with_scanvi(adata, model)
    # 5. Save the integrated adata and scANVI model
    scanvi_model.save(args.output_scanvi_dir, overwrite=True)
    # 6. Save the latent space
    adata.write_h5ad(filename=args.adata_output, compression="gzip")
    # 7. Save the cell types to feather
    # adata.obs[[args.predictions_key]].to_feather(args.output_cell_types_file, compression="gzip")
    # 7. Save the cell types to parquet
    adata.obs[[args.predictions_key]].to_parquet(args.output_cell_types_file, compression="gzip")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Leverage cell-type from MMC to assign the rest of the cells with scANVI")
    parser.add_argument(
        "--latent-key",
        type=str,
        required=True,
        help="Latent key to save the scANVI latent to",
    )
    parser.add_argument(
        "--predictions-key",
        type=str,
        required=True,
        help="scANVI cell type predictions column name in AnnData object",
    )
    parser.add_argument(
        "--adata-input",
        type=str,
        required=True,
        help="AnnData object for a dataset",
    )
    parser.add_argument(
        "--scvi-outputs-dir",
        type=str,
        required=True,
        help="Saved scVI outputs folder",
    )
    parser.add_argument(
        "--adata-output",
        type=str,
        required=True,
        help="Output file to save AnnData object to",
    )
    parser.add_argument(
        "--output-scanvi-dir",
        type=str,
        required=True,
        help="Output folder to save scANVI model",
    )
    parser.add_argument(
        "--output-cell-types-file",
        type=str,
        required=True,
        help="Output file to write cell types to",
    )

    args = parser.parse_args()
    main(args)
